### ISSUE TITLE
week 5 ready for review

### ISSUE THREAD

**Issue by jbjohnson2** [jbjohnson2/indieProject#2]
@pawaitemadisoncollege 
I did the week 5 hibernate work in this indie project instead of the exercise. I added a reviews database table, Review entity,  ReviewDAO, ReviewDAO Tests, and updated my hibernate config file with the new review entity.  There is a screenshot of my tests passing and code coverage in the weekly work screenshots.
1. My key learning point this week was debugging. 
2. I had some trouble getting my project to run, connect to the database, connect to the right database and other issues. 
3. To fix my problem, I referred the user exercise code from the demos and also just walked through the flow of my work to see where my issues were so that I could fix them .

**Comment by pawaitemadisoncollege** [comment]
Hi @jbjohnson2! Great job implementing hibernate into a one-to-many relationship in your indie project. This sets you up really well for checkpoint 2 which is due next week!

I noticed one test was commented out - were you debating how to handle "unattached" reviews? Did we chat about this already? What should happen to a user's reviews if the user id deleted? What if a review is deleted? Should the user stick around (probably?!). 

A good next step may be to implement the generic dao (I posted about this in slack last night), to eliminate the duplication your entity-specific daos. 

You should be really proud of all the progress you've made!!

**Comment by jbjohnson2** [comment]
I must have commented that test out and then forgot to go back to it. It is fixed and running now
