### ISSUE TITLE
Code Review #1 Ready!

### ISSUE THREAD

**Issue by redfoxanna** [jbjohnson2/indieProject#3]
Hi Jennifer! It was nice meeting with you yesterday. I have gone over the review form and copied it here for you to view. Hope you were able to get your new computer set up! 

# Design/Code Review 1

### Reviewer: Anna Kessler

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| You have your purpose defined clearly and understandable by the average person. I see no typos. You mention trails in your problem statement but I don't see a way to view/comment on trails in the park on the review form. We also discussed adding a way for a user to contribute an image of a campsite with their review|
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | Looking at your wireframes for this since you're still working on front end design/jsps. The form fields are logical and will be easy to use. Will you need another jsp for editing a review? You have a lot of tables with data in your application so I'm wondering if you tried out the jQuery datatables? There is a search component that filters REALLY nicely!|
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| You have a 1:many relationship with one user being able to leave many reviews. Did you think about if you want to be able to persist a review if a user deletes their account? Are you going to need any other classes/relationships in your database going forward? (Side note: I laughed at your review giving Lake Kegonsa all D's in your sample database because SAME)|
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverage.  7. No sensitive information is visible in the repository (secrets, passwords, etc). | Your jsps do not have any repeated code and I see you using the include directive to achieve this- nice! I see logging statements instead of Sytem.out.println and printStackTrace. No monster classes so far. Unit tests and code coverage looks good and I know you were working on creating a GenericDao to add to your application. Your database.properties and hibernate.cfg.xml has your username and password for your database. I think if you add these to your .gitignore and then follow the directions Paual posted in Slack about removing this history, you should be good!|

**Comment by pawaitemadisoncollege** [comment]
Hi @redfoxanna  Thank you for your thorough review of @jbjohnson2  's project so far. From the specificity of your comments and suggestions, it's clear you put in some time to thoroughly examine the project and you posed some thoughtful questions and observations. 

I did a quick search for the word "print" and noticed one file where logging should be implemented instead: https://github.com/jbjohnson2/indieProject/blob/580e6017b998ab5ca6c3b30ae15c08f46f1927c3/src/main/java/edu/matc/persistence/PropertiesLoader.java#L21. With the interface, it may make sense to throw the exception so the "implementer" can catch and handle (log).

**Comment by jbjohnson2** [comment]
Thanks for the feedback @redfoxanna;

I updated the propertiesLoader method to throw the exception @pawaitemadisoncollege .
