### ISSUE TITLE
Week 6 ready for review

### ISSUE THREAD

**Issue by jbjohnson2** [jbjohnson2/indieProject#4]
@pawaitemadisoncollege - my application is deployed to AWS
<img width="958" alt="week6" src="https://github.com/jbjohnson2/indieProject/assets/90119350/f8cc407b-d423-4803-b0d3-9db13c3f5bf6">

link to project:

site-reviewer-env.eba-3gxtj9rz.us-east-2.elasticbeanstalk.com 

Weekly reflection
1. AWS deployment. setting up a new environment
2. I struggled with the getting the user display exercise and my project working in my new environment.  I went through some of the previous weeks videos/exercises to find things that I needed to update and  realized that I had to update multiple config files, as well as work though other issues but both applications are finally up and working . 
3. The AWS deployment went relatively smoothly. I did have to create a key pair and instance profile. Darins post on slack helped me figure that out.

**Comment by pawaitemadisoncollege** [comment]
Great work getting your indie project deployed to AWS, @jbjohnson2! This sets you up really well for hitting the upcoming checkpoints! Your hard work is paying off :)

**Comment by pawaitemadisoncollege** [comment]
Oops, one more thing! Be sure to add your deployed url here: https://github.com/mad-ent-java-s24/student/blob/main/IndividualProjects.md 

Have a great weekend!

**Comment by jbjohnson2** [comment]
I added the deployed url to the student repository. Thanks!
